services:
  autosuggest-app:
    build: .
    container_name: autosuggest-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
